### ISSUE TITLE
OpenCore structure error in any EFI except #1 in the list

### ISSUE THREAD

**Issue by perez987** [Lovely-XPP/OCUpdater#2]
Good morning. Last code works fine but yesterday I tried it choosing the first EFI in the list.

Today I'm trying with 2 or 3 OpenCore EFI folders on different macOS disks and I am seeing a strange behaviour. Only first EFI in the list works as expected, without issues. 
But any EFI except 1 gets this error: `OpenCore Folder Structure is not complete, please check EFI patition`. And the scripts ends.

This is diskutil with 3 EFI (tried also with 2):

```python
[Warn] Detect More than 1 EFI Patition with OC Folder, Please choose one!
1. /dev/disk1 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk1
   1:                        EFI EFI                     209.7 MB   disk1s1
   2:                 Apple_APFS Container disk4         499.9 GB   disk1s2

2. /dev/disk2 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                 Apple_APFS Container disk5         499.9 GB   disk2s2

3. /dev/disk6 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk6
   1:                        EFI EFI                     209.7 MB   disk6s1
   2:                  Apple_HFS Install macOS Ventura   499.8 GB   disk6s2

0. exit

Please input 0 ~ 3 :2
```

Typing 2 or 3, I get this output:

```python
[Info] Preparing for running...
[Info] Data File Found...
[Info] Reading Data File...
[Error] OpenCore Folder Structure is not complete, please check EFI patition
[Info] The script is terminated.

[Info] (EFI partition) Volume EFI on disk2s1 unmounted.
[Info] The script is terminated.
```

All the EFI folders are identical, same structure and files, changing only serial numbers in config.plist.

Typing 1 the script runs fine.

**Comment by Lovely-XPP** [comment]
Would you change the code below in function `self.init()` (Line 529 ~ 537 in latest code)

```python
# get local data
try:
    self.local = self.get_local_data()
    self.install = len(self.local.keys())
except:
    print(self.Colors('[Error] OpenCore Folder Structure is not complete, please check EFI patition', fcolor='red'))
    print(self.Colors("[Info] The script is terminated.", fcolor='green'))
    print("")
    exit()
```

into 
```python
# get local data
self.local = self.get_local_data()
self.install = len(self.local.keys())
```

and check what exactly error

**Comment by perez987** [comment]
With this code (tell me if is it as you want):
```python
        # get local data
        # try:
        self.local = self.get_local_data()
        self.install = len(self.local.keys())
        # except:
        #    print(self.Colors('[Error] OpenCore Folder Structure is not complete, please check EFI patition', fcolor='red'))
        #    print(self.Colors("[Info] The script is terminated.", fcolor='green'))
        #    print("")
        #    exit()
```

This is the output:

```bash
Volume EFI on disk1s1 failed to unmount: dissented by PID 841 (/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mdsync)
Dissenter parent PPID 1 (/sbin/launchd)
Volume EFI on disk2s1 failed to unmount: dissented by PID 841 (/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mdsync)
Dissenter parent PPID 1 (/sbin/launchd)
Volume EFI on disk6s1 failed to unmount: dissented by PID 841 (/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mdsync)
Dissenter parent PPID 1 (/sbin/launchd)
######################################################################################
#                               OpenCore Updater V1.31                               #
######################################################################################

[Error] Not OpenCore Detected, please check EFI patition
[Info] The script is terminated.
```

After that, the 3 EFIs are mounted ?? and remain mounted on the Desktop.

**Comment by Lovely-XPP** [comment]
It's so strange, would you try it again

**Comment by perez987** [comment]
Tried just now, mounting 3rd partition:

```bash
disk6s1 was already unmounted
######################################################################################
#                               OpenCore Updater V1.31                               #
######################################################################################

[Info] Preparing for running...
[Info] Data File not Found, Downloading...
[Info] Downloading Done
[Info] Data File Found...
[Info] Reading Data File...
Traceback (most recent call last):
  File "/Users/yo/Downloads/OCUpdater-main/OCUpdater.py", line 1318, in <module>
    ocup.main()
  File "/Users/yo/Downloads/OCUpdater-main/OCUpdater.py", line 1154, in main
    self.init()
  File "/Users/yo/Downloads/OCUpdater-main/OCUpdater.py", line 531, in init
    self.local = self.get_local_data()
  File "/Users/yo/Downloads/OCUpdater-main/OCUpdater.py", line 159, in get_local_data
    time = self.get_time(oc)
  File "/Users/yo/Downloads/OCUpdater-main/OCUpdater.py", line 126, in get_time
    k_time = os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/EFI/EFI/OC/OpenCore.efi'
```

But, after this, EFI is really mounted on the Desktop.

**Comment by Lovely-XPP** [comment]
Yep, I set unmounted the EFI partition when quit script manually, so if it interrupts with error, the EFI can not be unmounted Automatically. By the way, may you give the exact directory of `OpenCore.efi` in your 3rd EFI partition.

**Comment by Lovely-XPP** [comment]
I think I have known the problem, wait a minute.

**Comment by Lovely-XPP** [comment]
I think mounting many EFI partitions will cause the issues, especially their volume name are the same. I have improved the code, you may try it and check if occurs other error.

**Comment by perez987** [comment]
The exact directory of `OpenCore.efi` is the same in the 3 EFIs. Folder structure is exactly the same.

<img width="472" alt="efi1" src="https://user-images.githubusercontent.com/50429399/201479258-759ed8a4-f843-4bb0-8c62-9f2244e1511d.png">

<img width="501" alt="efi2" src="https://user-images.githubusercontent.com/50429399/201479268-d5e1020e-1d17-4ea0-adbb-d67ff5c9695b.png">

<img width="523" alt="efi3" src="https://user-images.githubusercontent.com/50429399/201479273-b4174ae0-28dd-4f48-84de-3c7c4fb61c0e.png">

**Comment by perez987** [comment]
Last code outputs this just after entering the password in the first step of the script:

```bash
Volume EFI on disk0s1 force-unmounted
Traceback (most recent call last):
  File "/Users/yo/Downloads/OCUpdater-main/OCUpdater.py", line 1357, in <module>
    ocup.main()
  File "/Users/yo/Downloads/OCUpdater-main/OCUpdater.py", line 1192, in main
    self.init()
  File "/Users/yo/Downloads/OCUpdater-main/OCUpdater.py", line 499, in init
    self.mount_EFI()
  File "/Users/yo/Downloads/OCUpdater-main/OCUpdater.py", line 438, in mount_EFI
    os.system('echo ' + self.password + ' | sudo -S diskutil unmount force /dev/' + EFI_disk).read()
AttributeError: 'int' object has no attribute 'read'. Did you mean: 'real'?
```

disk0s1 is the first EFI seen by the system but it's the EFI of the Windows disk.
macOS EFIs are disk2s1, disk4s1 and disk6s1.

```bash
% /Users/yo > diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk0
   1:                        EFI EFI                     175.0 MB   disk0s1
   2:       Microsoft Basic Data WINDOWS                 499.3 GB   disk0s2
   3:           Windows Recovery                         636.5 MB   disk0s3

/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *500.1 GB   disk1
   1:               Windows_NTFS DATOS                   500.1 GB   disk1s1

/dev/disk2 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                 Apple_APFS Container disk3         499.9 GB   disk2s2

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +499.9 GB   disk3
                                 Physical Store disk2s2
   1:                APFS Volume macOS13G - Data         105.3 GB   disk3s1
   2:                APFS Volume macOS13G                8.8 GB     disk3s3
   3:              APFS Snapshot com.apple.os.update-... 8.8 GB     disk3s3s1
   4:                APFS Volume Preboot                 1.8 GB     disk3s4
   5:                APFS Volume Recovery                1.1 GB     disk3s5
   6:                APFS Volume VM                      1.1 MB     disk3s6

/dev/disk4 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk4
   1:                        EFI EFI                     209.7 MB   disk4s1
   2:                 Apple_APFS Container disk5         499.9 GB   disk4s2

/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +499.9 GB   disk5
                                 Physical Store disk4s2
   1:                APFS Volume macOS13 - Datos         122.0 GB   disk5s1
   2:                APFS Volume Preboot                 1.9 GB     disk5s2
   3:                APFS Volume Recovery                1.1 GB     disk5s3
   4:                APFS Volume macOS13                 8.8 GB     disk5s4
   5:                APFS Volume VM                      1.1 MB     disk5s6

/dev/disk6 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk6
   1:                        EFI EFI                     209.7 MB   disk6s1
   2:                  Apple_HFS Install macOS Ventura   499.8 GB   disk6s2
```

**Comment by Lovely-XPP** [comment]
sorry, it is a bug :(

**Comment by Lovely-XPP** [comment]
It should be okey now, you may try it again.  : )

**Comment by perez987** [comment]
Perfect!!! Tried different scenarios; only 1 macOS EFI / with 2 macOS EFIs / with 3 macOS EFIs.

Always first EFI seen by the system is the EFI of the Windows disk (set by BIOS, I guess), now disk1s1. Above the list of mounted EFIs, I see
`disk1s1 was already unmounted`
I suppose that it's the first EFI that's detected as Windows and unmounted. I don't see the code to do this but I'm not a coder.

All macOS EFIs are mounted according to the user choice.
All OpenCore folders are well analysed.
Up-to-date message is well displayed.
OpenCore or kexts update (if required)  also works well.

Congrats, I think the software now runs as expected. Thank you for your work!!!

**Comment by perez987** [comment]
This only for my understanding .

Lines 432-434:
```python
if not os.path.exists(source_path):
	os.system('echo ' + self.password + ' | sudo -S diskutil unmount force /dev/' + EFI_disk + ' >> /dev/null')
	os.system('echo ' + self.password + ' | sudo -S diskutil unmount force /dev/' + EFI_disk + ' >> /dev/null')
continue
```

Why there is twice the same line? Thank you very much.

**Comment by Lovely-XPP** [comment]
It is indeed duplicate, I deleted it in the latest commit. Thanks a lot.

**Comment by Lovely-XPP** [comment]
Here is the step of mounting and detecting OC EFI if you would like to know:

1. Get the identification of all EFI disks, by splitting words.
2. Mount the EFIs one by one, check if it exists `OC` folder. If so, save EFI disks and their OC directory to lists. After detecting, it is necessary to unmount it because of the possibility of duplicate EFI volume name.
3. Display all the detected EFI disks with OC folder and let user choose one.
4. Mount the chosen EFI disk and set it to property of the class. (self.EFI_disk & self.root)

**Comment by perez987** [comment]
Thank you! Good work.
